@ShoppingBasket.Server_HostAddress = https://localhost:7051

###
GET {{ShoppingBasket.Server_HostAddress}}/items
Accept: application/json

###
GET {{ShoppingBasket.Server_HostAddress}}/items/1
Accept: application/json

###
GET {{ShoppingBasket.Server_HostAddress}}/receipts
Accept: application/json

###
GET {{ShoppingBasket.Server_HostAddress}}/receipts/1
Accept: application/json

###
GET {{ShoppingBasket.Server_HostAddress}}/receipts/detailed/1
Accept: application/json

###
GET {{ShoppingBasket.Server_HostAddress}}/receipts/history
Accept: application/json

###

POST {{ShoppingBasket.Server_HostAddress}}/receipts
Content-Type: application/json
{
  "soupQuantity": 1,
  "breadQuantity": 1,
  "milkQuantity": 1,
  "applesQuantity": 1
}
###
